main:
  - name: About
    url: /ko/about/
    weight: 100

  - name: People
    url: /ko/people/
    weight: 200
  - parent: People
    name: Professor
    url: /ko/author/이경수/
    weight: 210
  - parent: People
    name: Members
    url: /ko/people/
    weight: 220

  - name: Research
    url: /ko/publication/
    weight: 300
  - parent: Research
    name: Publications
    url: /ko/publication/
    weight: 310
  - parent: Research
    name: Research Fields
    url: /ko/field/
    weight: 320

  - name: Inform
    url: /ko/post/
    weight: 600
  - parent: Inform
    name: Notifications
    url: /ko/notification/
    weight: 610
  - parent: Inform
    name: News
    url: /ko/post/
    weight: 620
  - parent: Inform
    name: Events
    url: /ko/event/
    weight: 630

  - name: Contact
    url: /ko/contact/
    weight: 700
