name = "Research Group"
license = "MIT"
licenselink = "https://github.com/HugoBlox/theme-documentation/blob/main/LICENSE.md"
description = "Easy,
all-in-one beautiful documentation website including a customizable homepage and blog. Super fast,
empowering you to focus on your content."

homepage = "https://github.com/wowchemy/starter-hugo-research-group"
demosite = "https://research-group.netlify.app/"

tags = [
"landing",
"docs",
"blog",
"responsive",
"minimal",
"light",
"dark",
"multilingual",
"dark mode",
"tailwind",
"company",
"gallery"
"academic",
        "university",
        "research",
        "publications",
        "widgets",
        "portfolio",
        "responsive",
        "clean",
        "company",
        "blog",
        "events",
        "minimal",
        "light",
        "dark",
        "multilingual",
        "landing page",
        "contact form",
        "mobile",
        "search",
        "presentation",
        "simple",
        "minimalist",
        "starter",
        "modern",
        "one page",
        "customizable",
        "technical",
        "slide"
]

features = [
"secure",
"fast",
"search",
"dark mode",
"widgets",
"page builder",
"widgets",
"themes",
"search",
"research publication system",
"filterable portfolio",
"blog",
"create courses",
"talks",
"events",
"slides",
"gallery",
"contact form"
]


# If the theme has a single author
[author]
  name = "George Cushen"
  homepage = "https://georgecushen.com/"
